apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kiali-server
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: kiali-server
    spec:
      destination:
        namespace: istio-system
        server: https://kubernetes.default.svc
      ignoreDifferences:
      - kind: ServiceAccount
        jsonPointers:
        - /imagePullSecrets
        - /secrets
      project: istio-system
      source:
        helm:
          valueFiles:
          - values.yaml
        path: .
        repoURL: https://github.com/mgcalvo-istio-demo/istio-kiali-server-argocd-helm.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - Replace=false
        - PruneLast=true
        - CreateNamespace=true
